const SKILL_LOGO: Record<string, string> = {
  React: 'react.svg',
  'React 18': 'react.svg',
  'Next.js': 'nextjs.svg',
  TanStack: 'tanstack.png',
  JavaScript: 'javascript.svg',
  TypeScript: 'typescript.svg',
  WebGL: 'webgl.svg',
  'Three.js': 'threejs.svg',
  R3F: 'threejs.svg',
  Drei: 'threejs.svg',
  Cannon: 'threejs.svg',
  'Cannon.js': 'threejs.svg',
  Rapier: 'rapier.svg',
  Rapier3D: 'rapier.svg',
  Raiper: 'rapier.svg',
  GLSL: 'glsl.svg',
  WASM: 'wasm.svg',
  'driver.js': 'driverjs.svg',
  CodeMirror: 'codemirror.svg',
  'CodeMirror 6': 'codemirror.svg',
  Vitest: 'vitest.svg',
  Vite: 'vitejs.svg',
  Webpack: 'webpack.svg',
  'React Router': 'reactrouter.svg',
  Zustand: 'zustand.svg',
  'Tailwind CSS': 'tailwindcss.svg',
  'Ant Design': 'antdesign.svg',
  Figma: 'figma.svg',
  'ESLint/TSLint': 'eslint.svg',
  Prettier: 'prettier.svg',
  'Node.js': 'nodejs.svg',
  NestJS: 'nestjs.svg',
  'Python 3': 'python.svg',
  Django: 'django.svg',
  FastAPI: 'fastapi.svg',
  Java: 'java.svg',
  'Spring Boot 3': 'spring.svg',
  MongoDB: 'mongodb.svg',
  Redis: 'redis.svg',
  MySQL: 'mysql.svg',
  Elasticsearch: 'elasticsearch.svg',
  Supabase: 'supabase.svg',
  Stripe: 'stripe.svg',
  'Swagger/Knife4j': 'swagger.svg',
  'Spring AI': 'spring.svg',
  'Spring AI Alibaba': 'spring.svg',
  Qdrant: 'qdrant.svg',
  OpenClaw: 'openclaw.svg',
  'Vercel AI SDK': 'vercel.svg',
  'OpenAI SDK': 'openai.svg',
  'Claude Code': 'claude.svg',
  Cursor: 'cursor.svg',
  'Open Code': 'opencode.svg',
  'Google Antigravity': 'google-antigravity.svg',
  'OpenAI Codex': 'openai.svg',
}

export const SKILL_ACCENTS = ['107,230,255', '67,231,177', '255,155,90', '167,139,250']

export function getSkillLogoSrc(label: string) {
  const filename = SKILL_LOGO[label]
  return filename ? `${import.meta.env.BASE_URL}logos/skills/${filename}` : undefined
}
