const SKILL_LOGO: Record<string, string> = {
  React: 'react.svg',
  'React 18': 'react.svg',
  'React 19': 'react.svg',
  'Next.js': 'nextjs.svg',
  Turbopack: 'turbopack.svg',
  'App Router': 'nextjs.svg',
  'next/link': 'nextjs.svg',
  'next/image': 'nextjs.svg',
  TanStack: 'tanstack.png',
  JavaScript: 'javascript.svg',
  TypeScript: 'typescript.svg',
  'TypeScript 5.5': 'typescript.svg',
  'Chakra UI': 'chakraui.svg',
  'Material UI': 'mui.svg',
  'Framer Motion': 'framer.svg',
  Axios: 'axios.svg',
  WebGL: 'webgl.svg',
  'Three.js': 'threejs.svg',
  R3F: 'threejs.svg',
  Drei: 'threejs.svg',
  Cannon: 'threejs.svg',
  'Cannon.js': 'threejs.svg',
  Rapier: 'rapier.svg',
  Rapier3D: 'rapier.svg',
  Raiper: 'rapier.svg',
  GLSL: 'glsl.svg',
  WASM: 'wasm.svg',
  'driver.js': 'driverjs.svg',
  CodeMirror: 'codemirror.svg',
  'CodeMirror 6': 'codemirror.svg',
  Vitest: 'vitest.svg',
  Vite: 'vitejs.svg',
  'Vite 6': 'vitejs.svg',
  Webpack: 'webpack.svg',
  'React Router': 'reactrouter.svg',
  'React Router 7': 'reactrouter.svg',
  'React Three Fiber': 'threejs.svg',
  'React Three Cannon': 'threejs.svg',
  'React Three Postprocessing': 'threejs.svg',
  Zustand: 'zustand.svg',
  'Zustand 5': 'zustand.svg',
  Immer: 'immer.svg',
  'Tailwind CSS': 'tailwindcss.svg',
  'Tailwind CSS 3': 'tailwindcss.svg',
  'Ant Design': 'antdesign.svg',
  'Ant Design 6': 'antdesign.svg',
  Figma: 'figma.svg',
  'React Hook Form': 'reacthookform.svg',
  Zod: 'zod.svg',
  'Socket.IO': 'socketio.svg',
  i18n: 'i18next.svg',
  i18next: 'i18next.svg',
  WebMCP: 'webmcp.svg',
  'ESLint/TSLint': 'eslint.svg',
  ESLint: 'eslint.svg',
  Prettier: 'prettier.svg',
  'Node.js': 'nodejs.svg',
  NestJS: 'nestjs.svg',
  'NestJS 10': 'nestjs.svg',
  'Python 3': 'python.svg',
  Django: 'django.svg',
  FastAPI: 'fastapi.svg',
  Java: 'java.svg',
  'Spring Boot': 'spring.svg',
  'Spring Boot 3': 'spring.svg',
  MongoDB: 'mongodb.svg',
  Redis: 'redis.svg',
  MySQL: 'mysql.svg',
  Elasticsearch: 'elasticsearch.svg',
  Supabase: 'supabase.svg',
  Stripe: 'stripe.svg',
  'Swagger/Knife4j': 'swagger.svg',
  Swagger: 'swagger.svg',
  'Spring AI': 'spring.svg',
  'Spring AI Alibaba': 'spring.svg',
  Qdrant: 'qdrant.svg',
  OpenClaw: 'openclaw.svg',
  'Vercel AI SDK': 'vercel.svg',
  'Anthropic SDK': 'claude.svg',
  OpenAI: 'openai.svg',
  'OpenAI SDK': 'openai.svg',
  'Google GenAI': 'googlegemini.svg',
  'Claude Code': 'claude.svg',
  Cursor: 'cursor.svg',
  'Open Code': 'opencode.svg',
  'Google Antigravity': 'google-antigravity.svg',
  'OpenAI Codex': 'openai.svg',
  'AWS EC2': 'awsec2.svg',
  'AWS S3': 'awss3.svg',
  'Route 53': 'route53.svg',
  'AWS ALB': 'awsalb.svg',
  'AWS CloudFront': 'cloudfront.svg',
  CloudFront: 'cloudfront.svg',
  Railway: 'railway.svg',
  Docker: 'docker.svg',
  JWT: 'jwt.svg',
  Jest: 'jest.svg',
}

export const SKILL_ACCENTS = ['107,230,255', '67,231,177', '255,155,90', '167,139,250']

export function getSkillLogoSrc(label: string) {
  const filename = SKILL_LOGO[label]
  return filename ? `${import.meta.env.BASE_URL}logos/skills/${filename}` : undefined
}
